name = "baidu-link-submitter"
main = "src/index.js"
compatibility_date = "2024-01-01"

[triggers]
crons = ["0 10 * * *"]  # 每天上午9点执行

[[kv_namespaces]]
binding = "SUBMITTED_LINKS"
id = "24e09d537b9d413ba5a0e0d3ac06df9f"
//preview_id = "your-preview-kv-namespace-id"

[vars]
BAIDU_SITE = "https://www.soliao.com"
BAIDU_TOKEN = "IRDNtnnEy5Cu8hzu"