name = "baidu-link-submitter"
main = "src/index.js"
compatibility_date = "2024-01-01"

[triggers]
crons = ["0 10 * * *"]  # 每天上午9点执行

[[kv_namespaces]]
binding = "SUBMITTED_LINKS"
id = "xxxxxx"
//preview_id = "your-preview-kv-namespace-id"

[vars]
BAIDU_SITE = "https://www.xxxx.com"

BAIDU_TOKEN = "xxx"
